URL_PAGE_TEXT_BOX = 'https://demoqa.com/text-box'
URL_PAGE_CHECK_BOX = 'https://demoqa.com/checkbox'
URL_PAGE_RADIO_BUTTON = 'https://demoqa.com/radio-button'
URL_WEB_TABLE_PAGE = 'https://demoqa.com/webtables'
URL_BUTTONS_PAGE = 'https://demoqa.com/buttons'
